<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Hecate</string>
    <key>scopeName</key>
    <string>source.hecate</string>
    <key>fileTypes</key>
    <array>
      <string>hec</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
<!--            <key>captures</key>-->
<!--            <dict>-->
<!--              <key>1</key>-->
<!--              <dict>-->
<!--                <key>name</key>-->
<!--                <string>punctuation.definition.comment.hecate</string>-->
<!--              </dict>-->
<!--            </dict>-->
            <key>match</key>
            <string>^\s*(#).*(?:\n)?</string>
            <key>name</key>
            <string>comment.line.hecate</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
<!--            <key>captures</key>-->
<!--            <dict>-->
<!--              <key>1</key>-->
<!--              <dict>-->
<!--                <key>name</key>-->
<!--                <string>punctuation.definition.comment.hecate</string>-->
<!--              </dict>-->
<!--            </dict>-->
            <key>match</key>
            <string>\b(let|del|and|or|null|this|flag)\b</string>
            <key>name</key>
            <string>keyword.control.hecate</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
              <key>begin</key>
              <string>"</string>
              <key>end</key>
              <string>"</string>
              <key>name</key>
              <string>string.quoted.double.hecate</string>
<!--              "contentName": "string.quoted.double.shell"-->
              <key>patterns</key>
              <array>
                  <dict>
                      <key>match</key>
                      <string>\\["\\n\[$]</string>
                      <key>name</key>
                      <string>constant.character.escape.hecate</string>
                  </dict>
              </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>

